### ISSUE TITLE
Not operator

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord-pip#10]
https://github.com/Schrodinger-Hat/ImageGoNord-pip/blob/0c58ca4b9794e1f2093469f31582f95c6b29dab3/ImageGoNord/GoNord.py#L137

You could use the not operator:

```python
 if (not os.path.exists('../palettes/Nord/')): 
```

**Comment by TheJoin95** [comment]
Uhm, maybe the right way to do it is:
`if (os.path.exists('../palettes/Nord/')): `

Because the exists method is returning a bool, always no matter what

**Comment by Wabri** [comment]
Is I know how it work the os.path.exists method, but you compare a boolean with another boolean.

You want to do something if is false so you need the not operator to do it.

**Comment by TheJoin95** [comment]
Aah, yes, now I see what you was saying.

Yes, you are right.
It's better to use the not operator. Let's change it into the future release

**Comment by TheJoin95** [comment]
Closing this as won't do
