### ISSUE TITLE
Aurora?

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord-pip#11]
https://github.com/Schrodinger-Hat/ImageGoNord-pip/blob/0c58ca4b9794e1f2093469f31582f95c6b29dab3/ImageGoNord/GoNord.py#L138

Why you open the Aurora file?

**Comment by TheJoin95** [comment]
When our package is delivered to a filesystem we should be able to import the Nord palette (shipped with the package).
Before v0.1.5 this could not happen correctly.

I added the pkg_resources and I'm verifying if everything is correctly setup by opening the first file of the NordPalette.
By opening the file I can get the right path pointing to the palette data folder :)

**Comment by Wabri** [comment]
Ok, I miss this step.
