### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by UstymUkhman** [Schrodinger-Hat/ImageGoNord-pip#2]
Hi there 👋.
First of all, nice tool guys, I really like it!

Links on the [website](https://ign.schrodinger-hat.it/) are broken 'cause they're pointing to a non existing repo on github: https://github.com/Schrodinger-Hat/ImageGoNord.

I'm referring to these ones:
- hosted on GitHub
- open an issue on GitHub

in the very end of home page.

**Comment by TheJoin95** [comment]
Hi @UstymUkhman, thank you for your feedback, we really appreciate that.

We fixed the issue! 

The repository was still a private repo, now it is public.
