### ISSUE TITLE
Incorrect dependency listed for "skimage"

### ISSUE THREAD

**Issue by JinEnMok** [Schrodinger-Hat/ImageGoNord-pip#23]
Your `setup.py`'s dependency array [currently points](https://github.com/Schrodinger-Hat/ImageGoNord-pip/blame/706b6545ac688172a97b6578cdb94a3d8052fe98/setup.py#L35) to `skimage`, while it should be pointing to `scikit-image`. The former produces an error during installation.

**Comment by TheJoin95** [comment]
Looking into it

**Comment by TheJoin95** [comment]
Fixed in v1.0.2
